sitegroup: DRUPAL-PROJECT-SITEGROUP
deploy_tasks:
  development:
    before_deploy:
      - composer install
      - cd web/themes/contrib/starterkit && npm ci
      - cd web/themes/contrib/starterkit && npm run gulp
    after_deploy:
      - cd web && drush -y updb --cache-clear=0
      - cd web && drush -y cim
      - cd web && drush -y cr
  production:
    before_deploy:
      - composer install
      - cd web/themes/contrib/starterkit && npm ci
      - cd web/themes/contrib/starterkit && npm run gulp
    after_deploy:
      - cd web && drush -y updb --cache-clear=0
      - cd web && drush -y cr

shared:
  production:
    - src: files
      dst: web/sites/default/files
versions:
  node: 10
