# Create here the Drupal site you would like
version: '2'
services:
  drupal:
    # Choose your URL and hostname for this Docker Container
    # NEEDS to end with '.docker.amazee.io' !
    # DO NOT remove the '&hostname'
    hostname: &hostname DRUPAL-PROJECT-DOMAIN.docker.amazee.io
    environment:
      # If you use https://github.com/drupal-composer/drupal-project or something similar,
      # the Drupal root is not inside the Repository root, you can define in which folder
      # the the Drupal Root lives
      WEBROOT: web

      # If you would like to use blackfire.io, uncomment and add your server credentials:
      BLACKFIRE_SERVER_ID: ffb6ed84-683d-4d5d-aebe-9f6f24f5554a
      BLACKFIRE_SERVER_TOKEN: 8a3f71a8b60153222ff1b4e2a07f8f1984875b093948b4050f9e1df6238966d6

      # APC Support is by default enabled, but in some cases it can make issues, change to 0 to disable:
      APC: 1

      # Set the production URL to make stage_file_proxy work
      AMAZEEIO_PRODUCTION_URL: 'DRUPAL-PROJECT-DOMAIN'


################################################
### Do not change anything below here, unless you know what you do
      VIRTUAL_HOST: *hostname
    image: amazeeio/drupal:php71-basic
    volumes:
      - .:/var/www/drupal/public_html:delegated
    volumes_from:
      - container:amazeeio-ssh-agent
    container_name: *hostname
    network_mode: bridge
    ports:
      - 3306
